### ISSUE TITLE
Displaying Dynamic data

### ISSUE THREAD

**Issue by bhaveshk023** [kamval/WINSTAR-WFxx#2]
I wanted to display an integer value on the screen using text_command function and that data is dynamic which changes on user input. How can i do that . Please help.

**Comment by bhaveshk023** [comment]
The response time after touching the screen and displaying next screen is also more. How can we reduce the response time.

**Comment by kamval** [comment]
> I wanted to display an integer value on the screen using text_command function and that data is dynamic which changes on user input. How can i do that . Please help.

Just convert your int to char or string when printing using text_command function.
